"use client";

import { ArrowDownRight, ArrowUpRight } from "@phosphor-icons/react";
import Image from "next/image";
import { KineticText } from "@/components/motion/kinetic-text";

export function Hero() {
  return <section id="inicio" aria-labelledby="inicio-titulo" className="site-grid relative min-h-[calc(100svh-4.5rem)] overflow-hidden border-b border-[var(--line)] md:min-h-[min(100svh,46rem)]"><div className="shell relative flex min-h-[calc(100svh-4.5rem)] flex-col justify-between py-6 md:min-h-[min(100svh,46rem)] md:py-12"><div className="flex items-center justify-between border-b border-[var(--line)] pb-4 mono text-[var(--muted)]"><span>Luiz Meneses</span><span>Brasil · 2026</span></div><div className="grid gap-7 py-8 md:grid-cols-12 md:items-end md:gap-10 md:py-24"><div className="md:col-span-10"><div className="hero-signature"><h1 id="inicio-titulo" className="display hero-title font-semibold"><KineticText className="hero-kinetic" text="Olá, sou o Luiz!" /></h1><Image src="/assets/logos/MenesesLuiz.webp" alt="Retrato ilustrado de Luiz Meneses" width={1024} height={1024} priority className="hero-portrait" /></div><p className="copy hero-context">Estudante de Engenharia de Software e Defesa Cibernética, com foco em desenvolvimento, cloud security e IA aplicada.</p></div><aside aria-hidden="true" className="signal-marker hidden lg:col-span-1 lg:col-start-12 lg:grid"><p className="mono">01<br />scroll</p><span /><span className="opacity-50" /></aside></div><div className="flex flex-col justify-between gap-4 border-t border-[var(--line)] pt-4 sm:flex-row sm:items-center"><p className="mono text-[var(--muted)]">Software · Security · Web</p><div className="flex flex-wrap gap-3"><a className="button-primary" href="#projetos"><KineticText text="Ver projetos" /> <ArrowDownRight size={17} aria-hidden="true" /></a><a className="button-secondary" href="#sobre"><KineticText text="Sobre mim" /> <ArrowUpRight size={16} aria-hidden="true" /></a></div></div></div></section>;
}
